"""add trend indexes

Revision ID: 0800a3c0d2ba
Revises: 09ce4dbad7c0
Create Date: 2026-03-11 03:29:22.861312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0800a3c0d2ba'
down_revision: Union[str, Sequence[str], None] = '09ce4dbad7c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_trend_burst', 'discovered_trends', ['burst_score'], unique=False)
    op.create_index('idx_trend_score', 'discovered_trends', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trend_score', table_name='discovered_trends')
    op.drop_index('idx_trend_burst', table_name='discovered_trends')
    # ### end Alembic commands ###
