"""add discovered trends table

Revision ID: 09ce4dbad7c0
Revises: 5f899913f690
Create Date: 2026-03-11 03:08:06.582463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ce4dbad7c0'
down_revision: Union[str, Sequence[str], None] = '5f899913f690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('burst_score', sa.Float(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phrase')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discovered_trends')
    # ### end Alembic commands ###
