"""add niche and niche_keyword table

Revision ID: 3e930b86d439
Revises: 5b2560d91231
Create Date: 2026-03-03 16:28:07.669674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e930b86d439'
down_revision: Union[str, Sequence[str], None] = '5b2560d91231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('niche_keywords', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('niche_keywords', sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_niche_keyword', 'niche_keywords', ['niche_id', 'keyword'])
    op.add_column('niches', sa.Column('region_code', sa.String(length=5), nullable=False))
    op.add_column('niches', sa.Column('scan_mode', sa.String(), nullable=False))
    op.add_column('niches', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('niches', sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('niches', 'last_scanned_at')
    op.drop_column('niches', 'is_active')
    op.drop_column('niches', 'scan_mode')
    op.drop_column('niches', 'region_code')
    op.drop_constraint('uq_niche_keyword', 'niche_keywords', type_='unique')
    op.drop_column('niche_keywords', 'last_scanned_at')
    op.drop_column('niche_keywords', 'is_active')
    # ### end Alembic commands ###
