"""added model for idea updated index and foreign key

Revision ID: 4b7e862c1666
Revises: 0800a3c0d2ba
Create Date: 2026-03-13 23:26:51.243174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7e862c1666'
down_revision: Union[str, Sequence[str], None] = '0800a3c0d2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('idea_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['discovered_trends.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trend_id', 'title', name='uq_trend_idea')
    )
    op.create_index(op.f('ix_trend_ideas_id'), 'trend_ideas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_ideas_id'), table_name='trend_ideas')
    op.drop_table('trend_ideas')
    # ### end Alembic commands ###
