"""added trend_videos

Revision ID: 56a13cc5e713
Revises: 823ecf7a2806
Create Date: 2026-03-10 05:07:21.404404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a13cc5e713'
down_revision: Union[str, Sequence[str], None] = '823ecf7a2806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('channel_title', sa.String(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('virality_score', sa.Float(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['niche_keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword_id', 'youtube_video_id', name='uq_keyword_video')
    )
    op.create_index(op.f('ix_trend_videos_id'), 'trend_videos', ['id'], unique=False)
    op.create_index(op.f('ix_trend_videos_keyword_id'), 'trend_videos', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_trend_videos_youtube_video_id'), 'trend_videos', ['youtube_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_videos_youtube_video_id'), table_name='trend_videos')
    op.drop_index(op.f('ix_trend_videos_keyword_id'), table_name='trend_videos')
    op.drop_index(op.f('ix_trend_videos_id'), table_name='trend_videos')
    op.drop_table('trend_videos')
    # ### end Alembic commands ###
