"""initial schema

Revision ID: 5b2560d91231
Revises: 
Create Date: 2026-03-02 21:59:27.098901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b2560d91231'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('seo_title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('reading_time', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('host_site', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('drafted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_description', sa.String(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('canonical_url', sa.String(), nullable=True),
    sa.Column('schema_type', sa.String(), nullable=True),
    sa.Column('open_graph_title', sa.String(), nullable=True),
    sa.Column('open_graph_description', sa.String(), nullable=True),
    sa.Column('open_graph_image', sa.String(), nullable=True),
    sa.Column('featured_image_url', sa.String(), nullable=True),
    sa.Column('image_alt_text', sa.String(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.create_table('email_otps',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_email_otps_email'), 'email_otps', ['email'], unique=False)
    op.create_table('niches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_niches_id'), 'niches', ['id'], unique=False)
    op.create_index(op.f('ix_niches_name'), 'niches', ['name'], unique=True)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_table('trend_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(length=255), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trend_breakdown', sa.Text(), nullable=True),
    sa.Column('explore_link', sa.Text(), nullable=True),
    sa.Column('is_growing', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('Open', 'Processed', 'Ignored', name='trendstatus'), nullable=True),
    sa.Column('draft_id', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trend')
    )
    op.create_index(op.f('ix_trend_items_id'), 'trend_items', ['id'], unique=False)
    op.create_table('niche_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_niche_keywords_id'), 'niche_keywords', ['id'], unique=False)
    op.create_table('volume_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trend_id'], ['trend_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trend_id', 'ts', name='uq_trend_volume_ts')
    )
    op.create_index(op.f('ix_volume_points_id'), 'volume_points', ['id'], unique=False)
    op.create_index(op.f('ix_volume_points_ts'), 'volume_points', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volume_points_ts'), table_name='volume_points')
    op.drop_index(op.f('ix_volume_points_id'), table_name='volume_points')
    op.drop_table('volume_points')
    op.drop_index(op.f('ix_niche_keywords_id'), table_name='niche_keywords')
    op.drop_table('niche_keywords')
    op.drop_index(op.f('ix_trend_items_id'), table_name='trend_items')
    op.drop_table('trend_items')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_niches_name'), table_name='niches')
    op.drop_index(op.f('ix_niches_id'), table_name='niches')
    op.drop_table('niches')
    op.drop_index(op.f('ix_email_otps_email'), table_name='email_otps')
    op.drop_table('email_otps')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
