"""add discovered trends table

Revision ID: 5f899913f690
Revises: 34164fd3938d
Create Date: 2026-03-11 02:58:26.399340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f899913f690'
down_revision: Union[str, Sequence[str], None] = '34164fd3938d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trend_videos', sa.Column('source', sa.String(), nullable=False, server_default='youtube'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trend_videos', 'source')
    # ### end Alembic commands ###
