"""updated youtube video model

Revision ID: 629d9bebfda8
Revises: 4b7e862c1666
Create Date: 2026-03-19 01:24:14.451779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629d9bebfda8'
down_revision: Union[str, Sequence[str], None] = '4b7e862c1666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trend_videos', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###

    # 2️⃣ Backfill existing rows (temporary fix)
    op.execute(
        "UPDATE trend_videos SET thumbnail_url = '' WHERE thumbnail_url IS NULL"
    )

    # 3️⃣ Make column NOT NULL
    op.alter_column(
        "trend_videos",
        "thumbnail_url",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trend_videos', 'thumbnail_url')
    # ### end Alembic commands ###
