"""updated model for saved popular videos

Revision ID: 8e5ef6acf3fd
Revises: 629d9bebfda8
Create Date: 2026-04-05 16:12:47.386606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5ef6acf3fd'
down_revision: Union[str, Sequence[str], None] = '629d9bebfda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trend_videos', sa.Column('region_code', sa.String(), nullable=True))
    op.alter_column('trend_videos', 'keyword_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('uq_keyword_video'), 'trend_videos', type_='unique')
    op.create_unique_constraint('uq_keyword_video', 'trend_videos', ['region_code', 'youtube_video_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_keyword_video', 'trend_videos', type_='unique')
    op.create_unique_constraint(op.f('uq_keyword_video'), 'trend_videos', ['keyword_id', 'youtube_video_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('trend_videos', 'keyword_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('trend_videos', 'region_code')
    # ### end Alembic commands ###
